### PR TITLE
dimmer: Add OXT 1-channel dimmer

### PR DESCRIPTION
**Pull request by michau-krakow**
This pull request is adding support for OXT (and possible many more other brands) dimmers.

Note: It depends on code added in esphome/esphome#6021 and corresponding documentation esphome/esphome-docs#3498

### CODE REVIEW

**Comment by michau-krakow** [comment]
HI @tekmaven, thanks for merging! Unfortunatelly, this device is dependent on my two other merge requests for esphome (esphome/esphome#6021) and documentation (esphome/esphome-docs#3498) so will not work until support for oxt-dimmer device class is merged in... Would you please take a look at those other pull requests as well?

**Comment by tekmaven** [comment]
Unfortunately, I only work on this repo.  I think it's ok to have this merged first, we could add a note to the page for example. 
 Or we can just revert it.   What do you think is best?

**Comment by nagyrobi** [comment]
It should be either reverted, or added a note that it needs to be used as an external component.
Additionally the config doesn't even work with the current version of the component...

**Comment by lightingman117** [comment]
The following is working [tested on physical hardware].

I recommend an edit to include the proper external_components as a temporary fix.

`esphome:
  name: dimmer
  friendly_name: "OXT Dimmer"

bk72xx:
  board: cb3s

external_components:
  - source:
      type: git
      url: https://github.com/michau-krakow/esphome.git
      ref: oxt-dimmer
    components: [ oxt_dimmer ]

# Disable UART logging - we need UART to talk to dimming MCU
logger:
  baud_rate: 0

api:
  encryption:
    key: !secret esphome_api_password

ota:
  - platform: esphome
    password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid_IOT
  password: !secret wifi_password_IOT

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "OXT Fallback"
    password: !secret fallback_password

web_server:
  version: 3

captive_portal:
  
uart:
  tx_pin: GPIO11 # rx_pin is not required (not used)
  baud_rate: 9600

light:
  - platform: oxt_dimmer
    channels:
    - name: lamp1
      id: lamp1
      min_value: 0
      max_value: 255
      sensing_pin:
        number: GPIO08 # for CB3S module
        inverted: true
        mode: input_pullup
      default_transition_length: 1s # tranistions would work!`

**Comment by nagyrobi** [comment]
Docs pr?

**Comment by lightingman117** [comment]
> Docs pr?

Is that permitted for someone else's component or device?

I've read the adding device guide, is there a guide for modifying one?

I think I have a full config ready to go.

It also fixes Jesse's issue of including the sensing pin inside the light platform.

**Comment by nagyrobi** [comment]
At least a comment in the docs PR please. Merging code without mergring appropriate doc uptades could result in nasty things.

**Pull request merged**
