### PR TITLE
Add Configuration for Duux Whisper Flex Ultimate Smart Fan (DXCF14)

### PR DESCRIPTION
**Pull request by GraafG**
This pull request introduces the configuration for the Duux Whisper Flex Ultimate Smart Fan (DXCF14), using the existing configuration for the DXCF10 model as a foundation, originally contributed by @frauhottelmann.

Key Enhancements:
- Oscillation Modes: The DXCF14 model supports multiple oscillation modes. These modes have been incorporated into the configuration to ensure accurate control and functionality.
- Additional Speeds: The DXCF14 offers more speed settings than the DXCF10. These additional speed options have been added to the configuration to fully support the fan's capabilities. 

This configuration aims to provide full compatibility and enhanced control for users of the DXCF14 model.

### CODE REVIEW

**Comment by stofakiller** [comment]
Hi,
The code for Duux Whisper can't be compiled, there are many duplicate keys in the code, eg Tuya:, fan: etc

**Comment by frauhottelmann** [comment]
I guess @GraafG forgot to remove the parts from my template. Just remove everything starting and including the first tuya line until and not including the second tuya line.

**Comment by stofakiller** [comment]
Hu I,Thanks, there were some settings, eg speed_count that are different 😉Do you have eg a picture or some else, so I know the pins on the chip to connect 🤷‍♂️Venlig hilsen/Best Regards,Jan LarsenDen 5. sep. 2024 kl. 20.59 skrev frauhottelmann ***@***.***>:﻿
I guess @GraafG forgot to remove the parts from my template. Just remove everything starting and including the first tuya line until and not including the second tuya line.

**Comment by frauhottelmann** [comment]
I have created #831 to correct the template.
@stofakiller with the Duux Whisper Flex I had to open the base and solder directly to the esp-chip. You can't miss it. You can check: https://esphome.io/guides/physical_device_connection#module-only

**Pull request merged**
