### PR TITLE
Add package for Narada NPFC batteries

### PR DESCRIPTION
**Pull request by RoganDawes**
Accessed using modbus via RS485.

### CODE REVIEW

**Comment by tekmaven** [comment]
Our CMS does not support this include syntax.  The error was: 
```
error "gatsby-transformer-yaml" threw an error while running the onCreateNode lifecycle:
unknown tag !<!include> at line 206, column 137:
```

**Comment by RoganDawes** [comment]
I realise it is not supported. However, this is legitimate esphome syntax. So, what is the way forward? How do we get the CMS to support this?

**Comment by tekmaven** [comment]
I took some time today to work with the CMS and see how to best do this.  I came up with adding the files to the markdown page in code blocks with title metadata so the filenames get displayed for those blocks.

**Comment by RoganDawes** [comment]
That's awesome, thank you!

**Pull request merged**
